CREATE TABLE [mapSolarSystems] 
(   [regionID] INTEGER,
   [constellationID] INTEGER,
   [solarSystemID] INTEGER,
   [solarSystemName] TEXT(100),
   [luminosity] FLOAT,
   [border] YESNO,
   [fringe] YESNO,
   [corridor] YESNO,
   [hub] YESNO,
   [international] YESNO,
   [regional] YESNO,
   [constellation] YESNO,
   [security] FLOAT,
   [factionID] INTEGER,
   [radius] FLOAT,
   [sunTypeID] INTEGER,
   [securityClass] TEXT(2) 

)
