CREATE TABLE [staStations] 
(   [stationID] INTEGER,
   [security] INTEGER,
   [dockingCostPerVolume] FLOAT,
   [maxShipVolumeDockable] FLOAT,
   [officeRentalCost] INTEGER,
   [operationID] INTEGER,
   [stationTypeID] INTEGER,
   [corporationID] INTEGER,
   [solarSystemID] INTEGER,
   [constellationID] INTEGER,
   [regionID] INTEGER,
   [stationName] TEXT(100),
   [reprocessingEfficiency] FLOAT,
   [reprocessingStationsTake] FLOAT,
   [reprocessingHangarFlag] INTEGER 

)
